services:
  database:
    image: mysql:8.0.32
    container_name: database
    network_mode: "host"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=MyReview
    restart: 'always'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  api:
    build: .
    container_name: my_review_api
    network_mode: "host"
    environment:
      - DATABASE_URL=mysql://root:password@localhost:3306/MyReview
    depends_on:
      database:
        condition: service_healthy
